name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          pip install apache-airflow-providers-snowflake
          pip install apache-airflow-providers-dbcloud
          pip install dbt
          # Install other dependencies if needed

      - name: Deploy Airflow DAG
        run: |
         
          mkdir -p ${{ secrets.AIRFLOW_DAGS_PATH }}
          cp -r ./dags/*.py ${{ secrets.AIRFLOW_DAGS_PATH }}

      - name: Deploy dbt Project
        run: |
       
          mkdir -p ${{ secrets.DBT_PROJECT_PATH }}
          cp -r ./dbt_project/* ${{ secrets.DBT_PROJECT_PATH }}

      - name: Deploy Snowflake Scripts
        run: |

          mkdir -p ${{ secrets.SNOWFLAKE_SCRIPTS_PATH }}
          cp -r ./snowflake_scripts/* ${{ secrets.SNOWFLAKE_SCRIPTS_PATH }}

      - name: Run dbt tests
        run: |
          cd ${{ secrets.DBT_PROJECT_PATH }}
          dbt run
          dbt test
        env:
          DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
          DBT_ACCOUNT_ID: ${{ secrets.DBT_ACCOUNT_ID }}

      - name: Notify deployment
        run: echo "Deployment completed successfully!"
       
